// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCds5e6NJftzIItpE1Q8ZkRgZwGlqlcS90',
    appId: '1:549591856286:web:72d37c9bd6d09eade1f78f',
    messagingSenderId: '549591856286',
    projectId: 'unimas-ecomarket',
    authDomain: 'unimas-ecomarket.firebaseapp.com',
    storageBucket: 'unimas-ecomarket.firebasestorage.app',
    measurementId: 'G-QEN5DZV2W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApUn6Q4jgurvHfzhvzUVlqFBnpQ3zfijs',
    appId: '1:549591856286:android:48cffb41c593cadbe1f78f',
    messagingSenderId: '549591856286',
    projectId: 'unimas-ecomarket',
    storageBucket: 'unimas-ecomarket.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAFsYRtSCOe5jLbBvLJvi_cijkvU0E_1s',
    appId: '1:549591856286:ios:f4bd04d2287d7726e1f78f',
    messagingSenderId: '549591856286',
    projectId: 'unimas-ecomarket',
    storageBucket: 'unimas-ecomarket.firebasestorage.app',
    iosBundleId: 'com.example.unimasEcomarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAFsYRtSCOe5jLbBvLJvi_cijkvU0E_1s',
    appId: '1:549591856286:ios:f4bd04d2287d7726e1f78f',
    messagingSenderId: '549591856286',
    projectId: 'unimas-ecomarket',
    storageBucket: 'unimas-ecomarket.firebasestorage.app',
    iosBundleId: 'com.example.unimasEcomarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCds5e6NJftzIItpE1Q8ZkRgZwGlqlcS90',
    appId: '1:549591856286:web:7600be47668c4839e1f78f',
    messagingSenderId: '549591856286',
    projectId: 'unimas-ecomarket',
    authDomain: 'unimas-ecomarket.firebaseapp.com',
    storageBucket: 'unimas-ecomarket.firebasestorage.app',
    measurementId: 'G-EX34Y9B1YZ',
  );

}